### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by AlexWaygood**
I really enjoyed reading the article, it's great!

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thank you! Let me know if you have any feedback or additional areas to be covered.

**Comment by AlexWaygood** [comment]
The only other feedback I have is this section:

> Therefore, I decided to go back to showing only the alias name in repr():
> 
> ```pycon
> >>> Expr
> Expr
> >>> Expr.__value__
> SimpleExpr | tuple[SimpleExpr, BinOp, Expr]
> ```

My initial reason was "huh, I can see the reason for getting rid of the evaluated value from the repr(), but I'd prefer the repr to be something like `<type alias "Expr">` rather than just `Expr`". That could make it easier for people playing around with things in the REPL to quickly identify the type of these objects.

When you say:

> This should usually make type aliases more readable when displayed in places like documentation

Are you taking specifically about the `help()` function? We could plausibly teach `help()` to look at the `__name__` attribute for type aliases,instead of just calling repr() on everything.

It might be good to flesh that bit out a little more 🙂

**Comment by JelleZijlstra** [comment]
That's a good point, and might be worth discussing more on the PR or even on Discourse. I'd be open to changing the repr(). As precedent though, note that the repr() of TypeVars is just the name.

> Are you taking specifically about the help() function?

I was thinking more of tools like Sphinx that show signatures. I'm not sure what you suggest would be easy in help(): you'd also have to make this change inside of unions and generic aliases. Though then again, `types.UnionType.__repr__` already special cases types (so it doesn't show `<class 'int'> | <class 'str'>`), so maybe it should special-case type aliases too.

**Comment by AlexWaygood** [comment]
It's late here; I'll try to find time to post on the PR tomorrow :)

**Comment by JelleZijlstra** [comment]
No hurry! I think the PR might not be the best forum, as this is more of a question of what's good for users, not about the exact implementation. I'll happily implement whatever the consensus turns out to be. Plus, the PR thread is already gargantuan :)

I'll push some changes to this page to clarify my thinking and call out possible alternatives.

**Pull request merged**
